import { defaultEstablishments } from "./establishments";
import type { SchoolLifeData, TimetableSlot } from "./school-life-types";

const TCH = "tch-adjoua";
const TCH2 = "tch-brou";
const YEAR = "sy-2026-2027";
const DEMO_DAY = new Date().toLocaleDateString("en-CA", { timeZone: "Africa/Abidjan" });
const DEMO_MONTH = DEMO_DAY.slice(0, 7);

function slot(
  id: string,
  classId: string,
  dayOfWeek: TimetableSlot["dayOfWeek"],
  startTime: string,
  endTime: string,
  subjectId: string,
  room: string,
  teacherId = TCH,
): TimetableSlot {
  return { id, classId, dayOfWeek, startTime, endTime, subjectId, teacherId, room };
}

export const schoolLifeSeed: SchoolLifeData = {
  schoolYears: [
    {
      id: "sy-2025-2026",
      label: "2025-2026",
      startDate: "2025-09-01",
      endDate: "2026-07-10",
      current: false,
    },
    {
      id: YEAR,
      label: "2026-2027",
      startDate: "2026-09-01",
      endDate: "2027-07-10",
      current: true,
    },
  ],
  currentSchoolYearId: YEAR,
  subjects: [
    { id: "sub-langage", name: "Langage oral", cycle: "Maternelle" },
    { id: "sub-graphisme", name: "Graphisme", cycle: "Maternelle" },
    { id: "sub-eveil", name: "Éveil", cycle: "Maternelle" },
    { id: "sub-motricite", name: "Motricité", cycle: "Maternelle" },
    { id: "sub-fr", name: "Français" },
    { id: "sub-maths", name: "Mathématiques" },
    { id: "sub-emc", name: "EMC" },
    { id: "sub-sciences", name: "Sciences" },
    { id: "sub-histgeo", name: "Histoire-Géographie" },
    { id: "sub-anglais", name: "Anglais" },
    { id: "sub-eps", name: "EPS" },
    { id: "sub-arts", name: "Arts plastiques" },
  ],
  teachers: [
    {
      id: TCH,
      email: "enseignant@lesetoiles.ci",
      password: "Enseignant2026!",
      displayName: "Adjoua N’Guessan",
      title: "Enseignante titulaire (démo — tous cycles)",
      classIds: ["cls-gs", "cls-ce2", "cls-6e"],
      subjectIds: [
        "sub-langage",
        "sub-graphisme",
        "sub-eveil",
        "sub-motricite",
        "sub-fr",
        "sub-maths",
        "sub-emc",
        "sub-sciences",
        "sub-histgeo",
        "sub-anglais",
        "sub-eps",
      ],
      phone: "à confirmer",
    },
    {
      id: "tch-brou",
      email: "koffi.brou@lesetoiles.ci",
      password: "Enseignant2026!",
      displayName: "Koffi Brou",
      title: "Surveillant · EPS",
      classIds: ["cls-ce2", "cls-6e"],
      subjectIds: ["sub-eps"],
      phone: "à confirmer",
    },
  ],
  establishments: defaultEstablishments(),
  classes: [
    {
      id: "cls-gs",
      name: "Grande section",
      cycle: "Maternelle",
      campus: "Maternelle Les Étoiles",
      establishmentId: "est-maternelle",
      schoolYearId: YEAR,
      room: "Salle GS",
    },
    {
      id: "cls-ce2",
      name: "CE2",
      cycle: "Primaire",
      campus: "Primaire Les Étoiles",
      establishmentId: "est-primaire",
      schoolYearId: YEAR,
      room: "Salle CE2",
    },
    {
      id: "cls-6e",
      name: "6ème",
      cycle: "Secondaire",
      campus: "Collège Les Étoiles (non ouvert)",
      establishmentId: "est-college",
      schoolYearId: YEAR,
      room: "Salle 6A",
    },
  ],
  parents: [
    {
      id: "par-kouadio",
      displayName: "Famille Coulibaly",
      password: "Parent2026!",
      phone: "07 11 22 33 01",
      studentIds: ["stu-ama"],
      moduleParentsActive: true,
    },
    {
      id: "par-yao",
      displayName: "Famille N’Guessan",
      password: "Parent2026!",
      phone: "07 11 22 33 02",
      studentIds: ["stu-marc"],
      moduleParentsActive: true,
    },
  ],
  students: [
    {
      id: "stu-ama",
      firstName: "Aïcha",
      lastName: "Coulibaly",
      classId: "cls-gs",
      matricule: "ETOILES-DEMO-001",
      parentId: "par-kouadio",
      parentName: "Famille Coulibaly",
      birthDate: "2020-03-12",
      birthPlace: "Bingerville",
      gender: "F",
      nationality: "Ivoirienne",
      fatherName: "Coulibaly Seydou",
      motherName: "Coulibaly Aminata",
      guardianName: "Famille Coulibaly",
      guardianPhone: "07 11 22 33 01",
    },
    { id: "stu-sarah", firstName: "Sarah", lastName: "Diallo", classId: "cls-gs", gender: "F" },
    { id: "stu-jean", firstName: "Jean", lastName: "Bamba", classId: "cls-gs", gender: "M" },
    { id: "stu-fatou", firstName: "Fatou", lastName: "Traoré", classId: "cls-gs", gender: "F" },
    {
      id: "stu-marc",
      firstName: "Koffi",
      lastName: "N’Guessan",
      classId: "cls-ce2",
      matricule: "ETOILES-DEMO-002",
      nationalMatricule: "CI-2022-00418",
      parentId: "par-yao",
      parentName: "Famille N’Guessan",
      birthDate: "2016-09-04",
      birthPlace: "Abidjan",
      gender: "M",
      nationality: "Ivoirienne",
      fatherName: "N’Guessan Jean",
      motherName: "N’Guessan Akissi",
      guardianName: "Famille N’Guessan",
      guardianPhone: "07 11 22 33 02",
      contactEmail: "famille.nguessan@example.com",
    },
    { id: "stu-chloe", firstName: "Chloé", lastName: "Mensah", classId: "cls-ce2", gender: "F" },
    { id: "stu-ibrahim", firstName: "Ibrahim", lastName: "Coulibaly", classId: "cls-ce2", gender: "M" },
    { id: "stu-awa", firstName: "Awa", lastName: "Koné", classId: "cls-ce2", gender: "F" },
    {
      id: "stu-yao",
      firstName: "Yao",
      lastName: "Kouassi",
      classId: "cls-6e",
      nationalMatricule: "CI-2020-11802",
      gender: "M",
      birthPlace: "Bouaké",
      nationality: "Ivoirienne",
    },
    { id: "stu-marie", firstName: "Marie", lastName: "N’Dri", classId: "cls-6e", gender: "F" },
  ],
  timetableSlots: [
    slot("edt-gs-lu-1", "cls-gs", 1, "08:00", "09:00", "sub-langage", "Salle GS"),
    slot("edt-gs-lu-2", "cls-gs", 1, "09:15", "10:15", "sub-graphisme", "Salle GS"),
    slot("edt-gs-ma-1", "cls-gs", 2, "08:00", "09:00", "sub-eveil", "Salle GS"),
    slot("edt-gs-ma-2", "cls-gs", 2, "09:15", "10:15", "sub-motricite", "Cour maternelle"),
    slot("edt-gs-me-1", "cls-gs", 3, "08:00", "09:00", "sub-langage", "Salle GS"),
    slot("edt-gs-je-1", "cls-gs", 4, "08:00", "09:00", "sub-graphisme", "Salle GS"),
    slot("edt-gs-ve-1", "cls-gs", 5, "08:00", "09:00", "sub-eveil", "Salle GS"),
    slot("edt-ce2-lu-1", "cls-ce2", 1, "07:30", "08:30", "sub-fr", "Salle CE2"),
    slot("edt-ce2-lu-2", "cls-ce2", 1, "08:30", "09:30", "sub-maths", "Salle CE2"),
    slot("edt-ce2-lu-3", "cls-ce2", 1, "10:00", "11:00", "sub-emc", "Salle CE2"),
    slot("edt-ce2-ma-1", "cls-ce2", 2, "07:30", "08:30", "sub-maths", "Salle CE2"),
    slot("edt-ce2-ma-2", "cls-ce2", 2, "08:30", "09:30", "sub-fr", "Salle CE2"),
    slot("edt-ce2-me-1", "cls-ce2", 3, "07:30", "08:30", "sub-sciences", "Salle CE2"),
    slot("edt-ce2-je-1", "cls-ce2", 4, "07:30", "08:30", "sub-histgeo", "Salle CE2"),
    slot("edt-ce2-ve-1", "cls-ce2", 5, "07:30", "08:30", "sub-eps", "Cour primaire", TCH2),
    slot("edt-6e-lu-1", "cls-6e", 1, "07:30", "08:30", "sub-fr", "Salle 6A"),
    slot("edt-6e-lu-2", "cls-6e", 1, "08:30", "09:30", "sub-maths", "Salle 6A"),
    slot("edt-6e-lu-3", "cls-6e", 1, "10:00", "11:00", "sub-anglais", "Salle 6A"),
    slot("edt-6e-ma-1", "cls-6e", 2, "07:30", "08:30", "sub-histgeo", "Salle 6A"),
    slot("edt-6e-ma-2", "cls-6e", 2, "08:30", "09:30", "sub-sciences", "Salle 6A"),
    slot("edt-6e-me-1", "cls-6e", 3, "07:30", "08:30", "sub-maths", "Salle 6A"),
    slot("edt-6e-je-1", "cls-6e", 4, "07:30", "08:30", "sub-fr", "Salle 6A"),
    slot("edt-6e-ve-1", "cls-6e", 5, "07:30", "08:30", "sub-eps", "Terrain", TCH2),
  ],
  feeTypes: [
    {
      id: "fee-sco-mat",
      name: "Mensualité scolarité",
      kind: "scolarite",
      amountFcfa: 25000,
      period: "Septembre 2026",
      cycle: "Maternelle",
    },
    {
      id: "fee-can-mat",
      name: "Cantine",
      kind: "cantine",
      amountFcfa: 15000,
      period: "Septembre 2026",
      cycle: "Maternelle",
    },
    {
      id: "fee-sco-pri",
      name: "Mensualité scolarité",
      kind: "scolarite",
      amountFcfa: 35000,
      period: "Septembre 2026",
      cycle: "Primaire",
    },
    {
      id: "fee-can-pri",
      name: "Cantine",
      kind: "cantine",
      amountFcfa: 18000,
      period: "Septembre 2026",
      cycle: "Primaire",
    },
    {
      id: "fee-sco-sec",
      name: "Mensualité scolarité",
      kind: "scolarite",
      amountFcfa: 45000,
      period: "Septembre 2026",
      cycle: "Secondaire",
    },
    {
      id: "fee-can-sec",
      name: "Cantine",
      kind: "cantine",
      amountFcfa: 20000,
      period: "Septembre 2026",
      cycle: "Secondaire",
    },
  ],
  invoices: [
    {
      id: "inv-ama-sco-09",
      studentId: "stu-ama",
      feeTypeId: "fee-sco-mat",
      kind: "scolarite",
      label: "Mensualité scolarité",
      period: "Septembre 2026",
      amountFcfa: 25000,
      status: "due",
      createdAt: "2026-08-01T08:00:00.000Z",
    },
    {
      id: "inv-ama-can-09",
      studentId: "stu-ama",
      feeTypeId: "fee-can-mat",
      kind: "cantine",
      label: "Cantine",
      period: "Septembre 2026",
      amountFcfa: 15000,
      status: "due",
      createdAt: "2026-08-01T08:00:00.000Z",
    },
    {
      id: "inv-marc-sco-09",
      studentId: "stu-marc",
      feeTypeId: "fee-sco-pri",
      kind: "scolarite",
      label: "Mensualité scolarité",
      period: "Septembre 2026",
      amountFcfa: 35000,
      status: "due",
      createdAt: "2026-08-01T08:00:00.000Z",
    },
    {
      id: "inv-marc-can-09",
      studentId: "stu-marc",
      feeTypeId: "fee-can-pri",
      kind: "cantine",
      label: "Cantine",
      period: "Septembre 2026",
      amountFcfa: 18000,
      status: "paid",
      createdAt: "2026-08-01T08:00:00.000Z",
    },
  ],
  bulletins: [
    {
      id: "bul-ama-t3",
      studentId: "stu-ama",
      period: "Trimestre 3 — 2025-2026",
      average: 16.5,
      comment:
        "Aïcha participe avec plaisir. Langage oral en progrès. Continuer les activités de graphisme à la maison.",
      createdAt: "2026-06-20T10:00:00.000Z",
      pdfPath: "generated",
    },
    {
      id: "bul-marc-t3",
      studentId: "stu-marc",
      period: "Trimestre 3 — 2025-2026",
      average: 14.8,
      comment: "Koffi est sérieux et soigné. Calculs en bonne voie. Relire les leçons de français le soir.",
      createdAt: "2026-06-20T10:05:00.000Z",
      pdfPath: "generated",
    },
  ],
  attendance: [
    {
      id: "att-gs-2026-08-13",
      date: "2026-08-13",
      classId: "cls-gs",
      teacherId: TCH,
      recordedAt: "2026-08-13T07:45:00.000Z",
      entries: [
        { studentId: "stu-ama", status: "present" },
        { studentId: "stu-sarah", status: "present" },
        { studentId: "stu-jean", status: "late" },
        { studentId: "stu-fatou", status: "present" },
      ],
    },
    {
      id: "att-gs-2026-08-14",
      date: "2026-08-14",
      classId: "cls-gs",
      teacherId: TCH,
      recordedAt: "2026-08-14T07:42:00.000Z",
      entries: [
        { studentId: "stu-ama", status: "absent" },
        { studentId: "stu-sarah", status: "present" },
        { studentId: "stu-jean", status: "present" },
        { studentId: "stu-fatou", status: "present" },
      ],
    },
    {
      id: "att-ce2-2026-08-14",
      date: "2026-08-14",
      classId: "cls-ce2",
      teacherId: TCH,
      recordedAt: "2026-08-14T07:50:00.000Z",
      entries: [
        { studentId: "stu-marc", status: "present" },
        { studentId: "stu-chloe", status: "present" },
        { studentId: "stu-ibrahim", status: "late" },
        { studentId: "stu-awa", status: "present" },
      ],
    },
    {
      id: "att-ce2-2026-08-15",
      date: "2026-08-15",
      classId: "cls-ce2",
      teacherId: TCH,
      recordedAt: "2026-08-15T07:48:00.000Z",
      entries: [
        { studentId: "stu-marc", status: "late" },
        { studentId: "stu-chloe", status: "present" },
        { studentId: "stu-ibrahim", status: "present" },
        { studentId: "stu-awa", status: "absent" },
      ],
    },
  ],
  homeworks: [
    {
      id: "hw-gs-lettres",
      classId: "cls-gs",
      teacherId: TCH,
      title: "Tracer les lettres A et M",
      description: "Sur le cahier de graphisme : 2 lignes de A, 2 lignes de M. Apporter le cahier lundi.",
      dueDate: "2026-08-18",
      createdAt: "2026-08-14T16:00:00.000Z",
      attachment: "hw-gs-lettres.pdf",
      attachmentName: "Fiche-lettres-A-et-M.pdf",
    },
    {
      id: "hw-ce2-maths",
      classId: "cls-ce2",
      teacherId: TCH,
      title: "Problèmes de maths — page 24",
      description: "Exercices 1 à 4. Montrer le raisonnement, pas seulement le résultat.",
      dueDate: "2026-08-19",
      createdAt: "2026-08-15T16:10:00.000Z",
      attachment: "hw-ce2-maths.pdf",
      attachmentName: "Exercices-page-24.pdf",
    },
    {
      id: "hw-ce2-lecture",
      classId: "cls-ce2",
      teacherId: TCH,
      title: "Lecture : « Le baobab de grand-père »",
      description: "Lire le texte deux fois. Préparer 3 phrases pour raconter l’histoire.",
      dueDate: "2026-08-20",
      createdAt: "2026-08-15T16:20:00.000Z",
    },
  ],
  grades: [
    {
      id: "gr-ama-langage",
      studentId: "stu-ama",
      teacherId: TCH,
      subject: "Langage oral",
      value: 17,
      maxValue: 20,
      period: "Trimestre 3 — 2025-2026",
      comment: "S’exprime plus clairement en petit groupe.",
      createdAt: "2026-06-10T09:00:00.000Z",
    },
    {
      id: "gr-ama-graphisme",
      studentId: "stu-ama",
      teacherId: TCH,
      subject: "Graphisme",
      value: 16,
      maxValue: 20,
      period: "Trimestre 3 — 2025-2026",
      comment: "Tenue du crayon en progrès.",
      createdAt: "2026-06-10T09:05:00.000Z",
    },
    {
      id: "gr-marc-maths",
      studentId: "stu-marc",
      teacherId: TCH,
      subject: "Mathématiques",
      value: 15,
      maxValue: 20,
      period: "Trimestre 3 — 2025-2026",
      comment: "Bonnes opérations. Attention aux unités.",
      createdAt: "2026-06-12T09:00:00.000Z",
    },
    {
      id: "gr-marc-fr",
      studentId: "stu-marc",
      teacherId: TCH,
      subject: "Français",
      value: 14.5,
      maxValue: 20,
      period: "Trimestre 3 — 2025-2026",
      comment: "Lecture fluide. Orthographe à retravailler.",
      createdAt: "2026-06-12T09:10:00.000Z",
    },
    {
      id: "gr-marc-emc",
      studentId: "stu-marc",
      teacherId: TCH,
      subject: "EMC",
      value: 16,
      maxValue: 20,
      period: "Trimestre 3 — 2025-2026",
      createdAt: "2026-06-12T09:15:00.000Z",
    },
    {
      id: "gr-marc-sci",
      studentId: "stu-marc",
      teacherId: TCH,
      subject: "Sciences",
      value: 15.5,
      maxValue: 20,
      period: "Trimestre 3 — 2025-2026",
      createdAt: "2026-06-12T09:18:00.000Z",
    },
    {
      id: "gr-marc-ang",
      studentId: "stu-marc",
      teacherId: TCH,
      subject: "Anglais",
      value: 13,
      maxValue: 20,
      period: "Trimestre 3 — 2025-2026",
      comment: "Lexique à enrichir.",
      createdAt: "2026-06-12T09:20:00.000Z",
    },
    {
      id: "gr-marc-eps",
      studentId: "stu-marc",
      teacherId: TCH2,
      subject: "EPS",
      value: 16,
      maxValue: 20,
      period: "Trimestre 3 — 2025-2026",
      createdAt: "2026-06-12T09:22:00.000Z",
    },
  ],
  messages: [
    {
      id: "msg-1",
      senderId: `teacher:${TCH}`,
      receiverId: "parent:stu-ama",
      studentId: "stu-ama",
      content:
        "Bonjour Famille Coulibaly, Aïcha a bien participé à l’atelier langage. Pensez au cahier de graphisme pour lundi.",
      createdAt: "2026-08-14T17:02:00.000Z",
    },
    {
      id: "msg-2",
      senderId: "parent:stu-ama",
      receiverId: `teacher:${TCH}`,
      studentId: "stu-ama",
      content: "Merci maîtresse. Aïcha était un peu fatiguée vendredi, d’où l’absence. Elle sera là lundi.",
      createdAt: "2026-08-15T08:11:00.000Z",
      readAt: "2026-08-15T08:30:00.000Z",
    },
    {
      id: "msg-3",
      senderId: "school:secretariat",
      receiverId: "parent:stu-marc",
      studentId: "stu-marc",
      content: "Rappel : la réunion parents-enseignants du CE2 a lieu mercredi 20 août à 16 h 30.",
      createdAt: "2026-08-15T11:00:00.000Z",
    },
  ],
  busLines: [
    {
      id: "bus-petit-prince",
      name: "Ligne Les Étoiles (maternelle)",
      driverName: "Yao Konan",
      plate: "CI-4428-BV",
      note: "Départ 06:25 — Bingerville — Adjamé",
      stops: [
        { id: "stop-ayo", name: "Adjamé-Bingerville", time: "06:25" },
        { id: "stop-marche", name: "Marché Bingerville", time: "06:40" },
        { id: "stop-pp", name: "Maternelle Les Étoiles", time: "06:55" },
      ],
      studentIds: ["stu-ama", "stu-sarah", "stu-jean"],
    },
    {
      id: "bus-primaire",
      name: "Ligne Les Étoiles (primaire)",
      driverName: "Koffi Brou",
      plate: "CI-1190-BV",
      note: "Départ 06:35 — cité → campus 2",
      stops: [
        { id: "stop-cite", name: "Cité Adjouffou", time: "06:35" },
        { id: "stop-mairie", name: "Mairie Bingerville", time: "06:50" },
        { id: "stop-pp2", name: "Primaire Les Étoiles", time: "07:05" },
      ],
      studentIds: ["stu-marc", "stu-chloe", "stu-ibrahim"],
    },
  ],
  transportLogs: [
    {
      id: "tlog-ama-board",
      studentId: "stu-ama",
      busId: "bus-petit-prince",
      date: DEMO_DAY,
      event: "boarded",
      note: "Stop Adjamé-Bingerville",
      recordedAt: `${DEMO_DAY}T06:28:00.000Z`,
      recordedBy: `teacher:${TCH2}`,
    },
    {
      id: "tlog-ama-arr",
      studentId: "stu-ama",
      busId: "bus-petit-prince",
      date: DEMO_DAY,
      event: "arrived",
      recordedAt: `${DEMO_DAY}T06:58:00.000Z`,
      recordedBy: `teacher:${TCH2}`,
    },
    {
      id: "tlog-marc-board",
      studentId: "stu-marc",
      busId: "bus-primaire",
      date: DEMO_DAY,
      event: "boarded",
      note: "Stop Cité Adjouffou",
      recordedAt: `${DEMO_DAY}T06:38:00.000Z`,
      recordedBy: `teacher:${TCH}`,
    },
  ],
  pickupAuths: [
    {
      id: "pick-ama-16",
      studentId: "stu-ama",
      date: DEMO_DAY,
      code: "ETOILES-A7K2",
      authorizedPerson: "Famille Coulibaly",
      authorizedPhone: "07 11 22 33 01",
      createdAt: `${DEMO_DAY}T06:10:00.000Z`,
      createdBy: "school:secretariat",
    },
    {
      id: "pick-marc-16",
      studentId: "stu-marc",
      date: DEMO_DAY,
      code: "ETOILES-M3P9",
      authorizedPerson: "Famille N’Guessan",
      authorizedPhone: "07 11 22 33 02",
      createdAt: `${DEMO_DAY}T06:12:00.000Z`,
      createdBy: `teacher:${TCH}`,
    },
  ],
  healthIncidents: [
    {
      id: "hlth-ama-fever",
      studentId: "stu-ama",
      kind: "fever",
      note: "Température 37,8 °C — repos en infirmerie, parents prévenus.",
      date: "2026-08-14",
      createdAt: "2026-08-14T10:20:00.000Z",
      recordedBy: `teacher:${TCH}`,
    },
    {
      id: "hlth-jean-injury",
      studentId: "stu-jean",
      kind: "injury",
      note: "Égratignure au genou à la récréation — désinfecté, reste en classe.",
      date: "2026-08-15",
      createdAt: "2026-08-15T10:05:00.000Z",
      recordedBy: `teacher:${TCH}`,
    },
  ],
  leaveRequests: [
    {
      id: "leave-adjoua-aug",
      staffId: "staff-adjoua",
      teacherId: TCH,
      type: "annual",
      startDate: "2026-08-24",
      endDate: "2026-08-26",
      reason: "Voyage familial à Bouaké.",
      status: "pending",
      createdAt: "2026-08-15T09:00:00.000Z",
    },
    {
      id: "leave-brou-sick",
      staffId: "staff-brou",
      teacherId: TCH2,
      type: "sick",
      startDate: "2026-08-10",
      endDate: "2026-08-11",
      reason: "Arrêt de 48 h.",
      status: "approved",
      adminNote: "Accordé — remplacement EPS par la titulaire.",
      createdAt: "2026-08-09T18:00:00.000Z",
      reviewedAt: "2026-08-09T19:10:00.000Z",
    },
    {
      id: "leave-aminata-pending",
      staffId: "staff-aminata",
      type: "personal",
      startDate: "2026-08-28",
      endDate: "2026-08-28",
      reason: "Rendez-vous administratif à Abidjan.",
      status: "pending",
      createdAt: "2026-08-18T11:00:00.000Z",
    },
  ],
  staffPresence: [
    {
      id: "pres-adjoua-16",
      staffId: "staff-adjoua",
      teacherId: TCH,
      date: DEMO_DAY,
      status: "present",
    },
    {
      id: "pres-brou-16",
      staffId: "staff-brou",
      teacherId: TCH2,
      date: DEMO_DAY,
      status: "late",
      note: "Arrivée 07:20 — bus primaire.",
    },
    {
      id: "pres-aminata-16",
      staffId: "staff-aminata",
      date: DEMO_DAY,
      status: "present",
    },
    {
      id: "pres-yao-16",
      staffId: "staff-yao",
      date: DEMO_DAY,
      status: "present",
      note: "Poste grille primaire.",
    },
  ],
  payrollNotes: [
    {
      id: "pay-adjoua-08",
      teacherId: TCH,
      staffId: "staff-adjoua",
      month: DEMO_MONTH,
      note: "Versement prévu le 28.",
    },
  ],
  staffProfiles: [
    {
      id: "staff-adjoua",
      firstName: "Adjoua",
      lastName: "N’Guessan",
      jobTitle: "enseignant",
      contractType: "cdi",
      status: "active",
      startDate: "2022-09-01",
      campus: "Maternelle Les Étoiles",
      establishmentId: "est-maternelle",
      teacherId: TCH,
      email: "enseignant@lesetoiles.ci",
      phone: "à confirmer",
      baseSalary: 280000,
      documents: [{ id: "doc-adjoua-cni", filename: "CNI-Adjoua.pdf", note: "Copie CNI 2024" }],
    },
    {
      id: "staff-brou",
      firstName: "Koffi",
      lastName: "Brou",
      jobTitle: "enseignant",
      contractType: "vacataire",
      status: "active",
      startDate: "2024-09-02",
      campus: "Primaire Les Étoiles",
      establishmentId: "est-primaire",
      teacherId: TCH2,
      email: "koffi.brou@lesetoiles.ci",
      phone: "à confirmer",
      baseSalary: 120000,
      documents: [{ id: "doc-brou-contrat", filename: "contrat-vacation.pdf", note: "Vacation EPS 2026" }],
    },
    {
      id: "staff-aminata",
      firstName: "Aminata",
      lastName: "Traoré",
      jobTitle: "atsem",
      contractType: "cdd",
      status: "active",
      startDate: "2024-09-02",
      campus: "Maternelle Les Étoiles",
      establishmentId: "est-maternelle",
      email: "aminata.traore@lesetoiles.ci",
      phone: "07 12 44 10 21",
      baseSalary: 95000,
      documents: [{ id: "doc-aminata-contrat", filename: "contrat-CDD.pdf", note: "CDD 2026-2027" }],
    },
    {
      id: "staff-yao",
      firstName: "Yao",
      lastName: "Kouamé",
      jobTitle: "gardien",
      contractType: "cdi",
      status: "active",
      startDate: "2021-01-15",
      campus: "Primaire Les Étoiles",
      establishmentId: "est-primaire",
      phone: "07 12 44 10 22",
      baseSalary: 80000,
      documents: [{ id: "doc-yao-cni", filename: "CNI-Yao.pdf", note: "Pièce d’identité" }],
      notes: "Poste nuit / grille parking.",
    },
  ],
  salaryAdvances: [
    {
      id: "adv-adjoua-08",
      staffId: "staff-adjoua",
      amount: 20000,
      reason: "Frais médicaux famille.",
      status: "approved",
      createdAt: "2026-08-05T10:00:00.000Z",
      reviewedAt: "2026-08-05T16:00:00.000Z",
    },
    {
      id: "adv-aminata-pending",
      staffId: "staff-aminata",
      amount: 15000,
      reason: "Avance rentrée scolaires enfants.",
      status: "pending",
      createdAt: "2026-08-17T09:30:00.000Z",
    },
  ],
  staffEvaluations: [
    {
      id: "eval-adjoua-t3",
      staffId: "staff-adjoua",
      date: "2026-06-20",
      score: 17,
      comment: "Très bon suivi des trois cycles. Ponctualité et pédagogie.",
      createdAt: "2026-06-20T14:00:00.000Z",
    },
  ],
  payRubriques: [
    { id: "rub-204", code: "204", name: "Indemnité de transport", type: "earning", amount: 15000 },
    { id: "rub-810", code: "810", name: "Régime Général (CNPS)", type: "deduction", percent: 6.3 },
    { id: "rub-512", code: "512", name: "Prélèvement divers (CMU)", type: "deduction", amount: 2000 },
  ],
  payrollRuns: [
    {
      id: "prun-2026-08",
      month: DEMO_MONTH,
      status: "validated",
      totalNet: 570775,
      createdAt: "2026-08-20T08:00:00.000Z",
    },
  ],
  payslips: [
    {
      id: "pslip-adjoua-08",
      payrollRunId: "prun-2026-08",
      staffId: "staff-adjoua",
      month: DEMO_MONTH,
      baseSalary: 280000,
      bonuses: 15000,
      deductions: 19640,
      advances: 20000,
      netPay: 255360,
      createdAt: "2026-08-20T08:00:00.000Z",
      lines: [
        { id: "pline-a-100", code: "100", label: "Salaire de base", kind: "earning", amount: 280000, base: 280000 },
        { id: "pline-a-204", code: "204", label: "Indemnité de transport", kind: "earning", amount: 15000, base: 15000 },
        { id: "pline-a-810", code: "810", label: "Régime Général (CNPS)", kind: "deduction", amount: 17640, base: 280000, rate: 6.3, rateLabel: "6,3%" },
        { id: "pline-a-512", code: "512", label: "Prélèvement divers (CMU)", kind: "deduction", amount: 2000, base: 2000 },
        { id: "pline-a-453", code: "453", label: "Avances", kind: "deduction", amount: 20000, base: 20000 },
      ],
    },
    {
      id: "pslip-brou-08",
      payrollRunId: "prun-2026-08",
      staffId: "staff-brou",
      month: DEMO_MONTH,
      baseSalary: 120000,
      bonuses: 15000,
      deductions: 9560,
      advances: 0,
      netPay: 125440,
      createdAt: "2026-08-20T08:00:00.000Z",
      lines: [
        { id: "pline-b-100", code: "100", label: "Salaire de base", kind: "earning", amount: 120000, base: 120000 },
        { id: "pline-b-204", code: "204", label: "Indemnité de transport", kind: "earning", amount: 15000, base: 15000 },
        { id: "pline-b-810", code: "810", label: "Régime Général (CNPS)", kind: "deduction", amount: 7560, base: 120000, rate: 6.3, rateLabel: "6,3%" },
        { id: "pline-b-512", code: "512", label: "Prélèvement divers (CMU)", kind: "deduction", amount: 2000, base: 2000 },
      ],
    },
    {
      id: "pslip-aminata-08",
      payrollRunId: "prun-2026-08",
      staffId: "staff-aminata",
      month: DEMO_MONTH,
      baseSalary: 95000,
      bonuses: 15000,
      deductions: 7985,
      advances: 0,
      netPay: 102015,
      createdAt: "2026-08-20T08:00:00.000Z",
      lines: [
        { id: "pline-m-100", code: "100", label: "Salaire de base", kind: "earning", amount: 95000, base: 95000 },
        { id: "pline-m-204", code: "204", label: "Indemnité de transport", kind: "earning", amount: 15000, base: 15000 },
        { id: "pline-m-810", code: "810", label: "Régime Général (CNPS)", kind: "deduction", amount: 5985, base: 95000, rate: 6.3, rateLabel: "6,3%" },
        { id: "pline-m-512", code: "512", label: "Prélèvement divers (CMU)", kind: "deduction", amount: 2000, base: 2000 },
      ],
    },
    {
      id: "pslip-yao-08",
      payrollRunId: "prun-2026-08",
      staffId: "staff-yao",
      month: DEMO_MONTH,
      baseSalary: 80000,
      bonuses: 15000,
      deductions: 7040,
      advances: 0,
      netPay: 87960,
      createdAt: "2026-08-20T08:00:00.000Z",
      lines: [
        { id: "pline-y-100", code: "100", label: "Salaire de base", kind: "earning", amount: 80000, base: 80000 },
        { id: "pline-y-204", code: "204", label: "Indemnité de transport", kind: "earning", amount: 15000, base: 15000 },
        { id: "pline-y-810", code: "810", label: "Régime Général (CNPS)", kind: "deduction", amount: 5040, base: 80000, rate: 6.3, rateLabel: "6,3%" },
        { id: "pline-y-512", code: "512", label: "Prélèvement divers (CMU)", kind: "deduction", amount: 2000, base: 2000 },
      ],
    },
  ],
  financeAccounts: [
    { id: "acc-caisse", name: "Caisse secrétariat", type: "cash", balance: 450000 },
    { id: "acc-wave", name: "Wave Les Étoiles", type: "wave", balance: 1250000 },
    { id: "acc-om", name: "Orange Money", type: "orange_money", balance: 380000 },
    { id: "acc-bank", name: "BICICI Les Étoiles", type: "bank", balance: 4200000 },
  ],
  expenseCategories: [
    { id: "cat-sco", name: "Scolarité", kind: "income" },
    { id: "cat-can", name: "Cantine", kind: "income" },
    { id: "cat-fourn", name: "Fournitures", kind: "expense" },
    { id: "cat-sal", name: "Salaires", kind: "expense" },
    { id: "cat-ent", name: "Entretien", kind: "expense" },
  ],
  financeTransactions: [
    {
      id: "ftx-marc-can",
      type: "in",
      accountId: "acc-caisse",
      categoryId: "cat-can",
      date: "2026-08-18",
      label: "Caisse — Koffi N’Guessan — Cantine",
      amount: 18000,
      invoiceId: "inv-marc-can-09",
      reference: "inv-marc-can-09",
      createdAt: "2026-08-18T09:15:00.000Z",
    },
    {
      id: "ftx-craie",
      type: "out",
      accountId: "acc-caisse",
      categoryId: "cat-fourn",
      date: "2026-08-12",
      label: "Craies et cahiers GS",
      amount: 45000,
      createdAt: "2026-08-12T11:00:00.000Z",
    },
    {
      id: "ftx-wave-sco",
      type: "in",
      accountId: "acc-wave",
      categoryId: "cat-sco",
      date: "2026-08-10",
      label: "Scolarité Wave — familles CE2",
      amount: 140000,
      createdAt: "2026-08-10T16:40:00.000Z",
    },
  ],
  supplierInvoices: [
    {
      id: "sinv-papeterie",
      supplier: "Papeterie Adjamé-Bingerville",
      amount: 85000,
      status: "pending",
      dueDate: "2026-09-05",
      description: "Cahiers et cartouches rentrée",
      categoryId: "cat-fourn",
      createdAt: "2026-08-08T10:00:00.000Z",
    },
    {
      id: "sinv-jardin",
      supplier: "Espaces verts Bingerville",
      amount: 40000,
      status: "paid",
      dueDate: "2026-08-10",
      description: "Tonte cour maternelle",
      categoryId: "cat-ent",
      paidAt: "2026-08-11T12:00:00.000Z",
      accountId: "acc-caisse",
      createdAt: "2026-08-04T10:00:00.000Z",
    },
  ],
  budgetLines: [
    { id: "bud-fourn-26", categoryId: "cat-fourn", plannedAmount: 500000, year: "2026-2027" },
    { id: "bud-sal-26", categoryId: "cat-sal", plannedAmount: 6000000, year: "2026-2027" },
    { id: "bud-ent-26", categoryId: "cat-ent", plannedAmount: 300000, year: "2026-2027" },
    { id: "bud-sco-26", categoryId: "cat-sco", plannedAmount: 8500000, year: "2026-2027" },
  ],
  socialCases: [
    {
      id: "cas-ama",
      studentId: "stu-ama",
      motif: "precarite",
      discountType: "percent",
      discountValue: 25,
      note: "Suivi censeur — prise en charge oncle.",
      status: "actif",
      createdAt: "2026-08-02T09:00:00.000Z",
    },
  ],
  lostItems: [
    {
      id: "lost-gourde",
      description: "Gourde bleue Thermos, sticker ananas",
      place: "Cour maternelle",
      foundAt: "2026-08-15",
      createdAt: "2026-08-15T12:30:00.000Z",
      recordedBy: `teacher:${TCH}`,
      photo: "/images/lost-items/gourde.svg",
      claimed: false,
    },
    {
      id: "lost-sweat",
      description: "Sweat gris Les Étoiles, taille 8 ans",
      place: "Salle CE2",
      foundAt: "2026-08-14",
      createdAt: "2026-08-14T16:00:00.000Z",
      recordedBy: "school:secretariat",
      photo: "/images/lost-items/sweat.svg",
      claimed: false,
    },
    {
      id: "lost-cartable",
      description: "Cartable rouge avec stickers football",
      place: "Parking primaire",
      foundAt: "2026-08-13",
      createdAt: "2026-08-13T17:10:00.000Z",
      recordedBy: `teacher:${TCH2}`,
      photo: "/images/lost-items/cartable.svg",
      claimed: true,
      claimedByParentId: "par-yao",
      claimedAt: "2026-08-14T07:40:00.000Z",
    },
  ],
  enrollments: [
    {
      id: "enr-ama",
      studentId: "stu-ama",
      schoolYearId: YEAR,
      enrolledAt: "2026-08-28",
      enrollmentStatus: "NOUVEAU",
      isScholarship: false,
      repeatYear: false,
      documentsChecklist: {
        photos: true,
        extraitNaissance: true,
        visiteMedicale: true,
        carnetCorrespondance: false,
      },
      notes: "Première rentrée à la maternelle Les Étoiles.",
    },
    {
      id: "enr-marc",
      studentId: "stu-marc",
      schoolYearId: YEAR,
      enrolledAt: "2026-08-25",
      enrollmentStatus: "REINSCRIPTION",
      lv2: "ANGLAIS",
      birthCertNumber: "2016-B-4418",
      birthCertDate: "2016-09-20",
      birthCertPlace: "Abidjan",
      isScholarship: false,
      repeatYear: false,
      documentsChecklist: {
        photos: true,
        extraitNaissance: true,
        certificatScolarite: true,
        carnetCorrespondance: true,
        livretScolaire: true,
        inscriptionLigne: true,
      },
    },
    {
      id: "enr-yao",
      studentId: "stu-yao",
      schoolYearId: YEAR,
      enrolledAt: "2026-09-02",
      enrollmentStatus: "TRANSFERT",
      lv2: "ANGLAIS",
      previousSchool: "Collège Sainte-Marie, Bouaké",
      previousClass: "CM2",
      transferRef: "TRF-2026-014",
      isScholarship: false,
      repeatYear: false,
      documentsChecklist: {
        photos: true,
        extraitNaissance: true,
        certificatScolarite: true,
        livretScolaire: true,
      },
      notes: "Arrivée au collège Les Étoiles (ouverture).",
    },
  ],
  teacherControlEnabled: true,
  teacherControlNoMessageDays: 7,
  lessonValidations: [
    {
      id: "lval-adj-0824-gs",
      teacherId: TCH,
      slotId: "edt-gs-lu-1",
      date: "2026-08-24",
      classId: "cls-gs",
      subjectId: "sub-langage",
      chapter: "Les prénoms de la classe",
      content: "Chacun s’est présenté. Comptine des prénoms, puis jeux d’écoute.",
      validatedAt: "2026-08-24T09:05:00.000Z",
    },
    {
      id: "lval-adj-0824-ce2",
      teacherId: TCH,
      slotId: "edt-ce2-lu-1",
      date: "2026-08-24",
      classId: "cls-ce2",
      subjectId: "sub-fr",
      chapter: "Le baobab de grand-père",
      content: "Lecture suivie, vocabulaire, et préparation du résumé oral.",
      validatedAt: "2026-08-24T08:35:00.000Z",
    },
    {
      id: "lval-adj-0825-maths",
      teacherId: TCH,
      slotId: "edt-ce2-ma-1",
      date: "2026-08-25",
      classId: "cls-ce2",
      subjectId: "sub-maths",
      chapter: "Les unités de mesure",
      content: "Conversions m / cm. Exercices 1 à 3 du cahier.",
      validatedAt: "2026-08-25T08:32:00.000Z",
    },
  ],
  assessments: [
    {
      id: "asm-ce2-maths",
      teacherId: TCH,
      classId: "cls-ce2",
      subjectId: "sub-maths",
      kind: "controle",
      date: "2026-08-20",
      topic: "Opérations posées et problèmes de la page 24",
      status: "fait",
      validated: true,
      createdAt: "2026-08-12T10:00:00.000Z",
      submittedAt: "2026-08-20T11:00:00.000Z",
    },
    {
      id: "asm-6e-fr",
      teacherId: TCH,
      classId: "cls-6e",
      subjectId: "sub-fr",
      kind: "composition",
      date: "2026-08-28",
      topic: "Dictée et rédaction : un souvenir de vacances",
      status: "planifie",
      validated: false,
      createdAt: "2026-08-18T09:00:00.000Z",
    },
    {
      id: "asm-gs-langage",
      teacherId: TCH,
      classId: "cls-gs",
      subjectId: "sub-langage",
      kind: "controle",
      date: "2026-08-22",
      topic: "Comptines et vocabulaire de la rentrée",
      status: "en_retard",
      validated: false,
      createdAt: "2026-08-10T09:00:00.000Z",
    },
  ],
  activityLogs: [
    {
      id: "log-adj-login-0825",
      at: "2026-08-25T07:12:00.000Z",
      actorId: `teacher:${TCH}`,
      actorRole: "teacher",
      action: "login",
      payload: { teacherId: TCH, date: "2026-08-25" },
    },
    {
      id: "log-adj-lesson-0825",
      at: "2026-08-25T08:32:00.000Z",
      actorId: `teacher:${TCH}`,
      actorRole: "teacher",
      action: "validate_lesson",
      payload: {
        validationId: "lval-adj-0825-maths",
        slotId: "edt-ce2-ma-1",
        date: "2026-08-25",
        classId: "cls-ce2",
        subjectId: "sub-maths",
      },
    },
    {
      id: "log-adj-hw",
      at: "2026-08-15T16:10:00.000Z",
      actorId: `teacher:${TCH}`,
      actorRole: "teacher",
      action: "homework_create",
      payload: {
        homeworkId: "hw-ce2-maths",
        classId: "cls-ce2",
        title: "Problèmes de maths — page 24",
        dueDate: "2026-08-19",
      },
    },
    {
      id: "log-adj-grade",
      at: "2026-06-12T09:00:00.000Z",
      actorId: `teacher:${TCH}`,
      actorRole: "teacher",
      action: "grade_save",
      payload: {
        gradeId: "gr-marc-maths",
        studentId: "stu-marc",
        subject: "Mathématiques",
        period: "Trimestre 3 — 2025-2026",
        value: 15,
      },
    },
    {
      id: "log-adj-msg",
      at: "2026-08-14T17:02:00.000Z",
      actorId: `teacher:${TCH}`,
      actorRole: "teacher",
      action: "message_send",
      payload: { messageId: "msg-1", receiverId: "parent:stu-ama", studentId: "stu-ama" },
    },
    {
      id: "log-adj-asm",
      at: "2026-08-20T11:00:00.000Z",
      actorId: `teacher:${TCH}`,
      actorRole: "teacher",
      action: "assessment_submit",
      payload: {
        assessmentId: "asm-ce2-maths",
        classId: "cls-ce2",
        subjectId: "sub-maths",
        kind: "controle",
        date: "2026-08-20",
        validated: true,
      },
    },
  ],
  moduleControl: {
    modules: [],
    overrides: [],
    history: [],
  },
  cashPayments: [],
};
